// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServerProj.Models;

namespace ServerProj.Migrations
{
    [DbContext(typeof(CentaarContext))]
    partial class CentaarContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ServerProj.Models.Biblioteka", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NazivBiblioteke")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Naziv Biblioteke");

                    b.HasKey("ID");

                    b.ToTable("Biblioteka");
                });

            modelBuilder.Entity("ServerProj.Models.Knjiga", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BojaKnjige")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BojaKnjige");

                    b.Property<string>("ImeAutora")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ImeAutora");

                    b.Property<string>("ImeKnjige")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ImeKnjige");

                    b.Property<int?>("PolicaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PolicaID");

                    b.ToTable("Knjiga");
                });

            modelBuilder.Entity("ServerProj.Models.Polica", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BibliotekaID")
                        .HasColumnType("int");

                    b.Property<string>("ImePolice")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Ime Police");

                    b.Property<int>("MaksBrKnjiga")
                        .HasColumnType("int")
                        .HasColumnName("MaksimalniBrKnjiga");

                    b.HasKey("ID");

                    b.HasIndex("BibliotekaID");

                    b.ToTable("Polica");
                });

            modelBuilder.Entity("ServerProj.Models.Knjiga", b =>
                {
                    b.HasOne("ServerProj.Models.Polica", "Polica")
                        .WithMany("Knjige")
                        .HasForeignKey("PolicaID");

                    b.Navigation("Polica");
                });

            modelBuilder.Entity("ServerProj.Models.Polica", b =>
                {
                    b.HasOne("ServerProj.Models.Biblioteka", "Biblioteka")
                        .WithMany("Police")
                        .HasForeignKey("BibliotekaID");

                    b.Navigation("Biblioteka");
                });

            modelBuilder.Entity("ServerProj.Models.Biblioteka", b =>
                {
                    b.Navigation("Police");
                });

            modelBuilder.Entity("ServerProj.Models.Polica", b =>
                {
                    b.Navigation("Knjige");
                });
#pragma warning restore 612, 618
        }
    }
}
